### PR TITLE
Makefile

### PR DESCRIPTION
**Pull request by abchk1234**
Add basic `makefile`.

@apayne what do you think, is it ok?

### CODE REVIEW

**Comment by apayne** [comment]
It looks great!  But the uninstall doesn't remove the service directories.  Do you want that?  Or should the directories remain after installation?

My thought on it is, if the definitions are being removed, most likely the service management and the supervisor are being changed out completely.

**Comment by abchk1234** [comment]
From my limited experience, most packages do not remove files from _/etc_. Rather the package managers have a special option (like `--purge` in case of apt) to remove the configuration files. So I think we should let the files be.

Also if a user removes the services while they are under supervision, it might cause issue. The safer option would be to simply `rm -r /etc/svcdef` once the user has ensured that they dont want it further.

Can add a comment(echo) in the makefile with this information.

**Comment by abchk1234** [comment]
Thanks for your valuable feedback @apayne .

If we need to iterate further on it do let me know.

**Comment by apayne** [comment]
I'm sorry I haven't responded sooner - it's been rather busy at work!

The notification should be adequate.  Thanks for doing that.

**Pull request merged**
