### PR TITLE
Update services

### PR DESCRIPTION
**Pull request by abchk1234**

### CODE REVIEW

**Comment by apayne** [comment]
There is a check run for postfix, I've not pulled and run the code yet.  Do we need it there?
rsyslogd I believe writes to its own log files - we could probably drop the log for it.

**Comment by abchk1234** [comment]
The postfix check is not compulsory. I removed it and the service still started. I dont know though what happens when the check fails and one tries to bring up the service. Since the check is not present in simimlae services like httpd, will remove it here too.

rsyslogd does not log to stdout as you correctly said. I added it in case a user want to debug it and log to stderr. In such case user can add the log service too. Will remove it as default.

**Comment by abchk1234** [comment]
Reading about `postfix check` in the man page, it does more than simply checking:

~~~~
       The following commands are implemented:

       check  Warn about bad directory/file ownership or permissions, and create missing directories.
~~~~

So I think we can keep the check. Will revert the rsyslog log change.

**Comment by apayne** [comment]
Re: postfix check, that's fine then, it is a "sanity check" to ensure there is a clean environment prior to start.

Re: syslog, that's good too.

**Pull request merged**
